baseurl = "https://dominiquealis.github.io/portfolio/"
languageCode = "en-us"
title = "Dominique A. Ryan"
theme = "hugo-strata-theme"
disqusShortname = "dominiquealis"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Dominique Ryan"
	description = "Dominique Ryan Portfolio"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "selfpic.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Dominique A. Ryan"
		# The icons will be shown if you enter your username
		github = "dominiquealis"
		facebook = "dominiquealis"
		linkedin = "https://www.linkedin.com/in/dominique-ryan-765b669"

		copyright = [
			"&copy; Dominique Ryan",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "About"
		content = "Hello, I'm Dominique Ryan. I currently live in Silver Spring, Maryland with my husband and our three cats. When not working my interests are knitting, cooking, gardening, and television. Recently I've made it a goal to learn more about front-end development."


	[params.work]
		hide  = false
		title = "Work Experience"



	[params.portfolio]
		hide  = false
		title = "Recent Projects"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/hometest.png"
			thumb = "fulls/hometest.png"
			url = "https://github.com/dominiquealis/NeighborhoodProjectApp"
			title = "Neighborly"
			description = "A simplifed way to stay in touch with your neighbors"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			url = "https://github.com/dominiquealis/NeighborhoodProjectApp"
			title = "Relaxr"
			description = "Relax. Let us take care of it."

		[[params.portfolio.gallery]]
			thumb = "thumbs/quince.jpg"
			url = "https://github.com/dominiquealis/NeighborhoodProjectApp"
			title = "Where my stitches at?"
			description = "Fellow knitter? Check out some of my projects on Ravelry."

	[params.recentposts]
		hide  = false
		title = "Recent Updates"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Send me a message. I love getting mail!"

		address = [
			"712 Ritchie Ave",
			"Silver Spring, MD 20910",
			"United States"
		]
		phone = "240-393-3687"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "dominique.ryan@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "E-mail"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0


[[menu.main]]
	name = "Updates"
	url  = "post/"
	weight = 10